name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & Verify (tests + SpotBugs + OWASP DepCheck)
        run: mvn -B clean verify

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: |
            target/spotbugsXml.xml
            **/target/spotbugsXml.xml
          if-no-files-found: warn

      - name: Upload Dependency-Check reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.json
            target/dependency-check-report.xml
          if-no-files-found: warn
